server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://101.201.150.84:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: blog
    password: FieG6LWZ5FyErHhy
  jackson:
    # 时间格式化
    date-format: yyyy-MM-dd
    # 时区
    time-zone: GMT+8
    locale: zh_CN
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

yunxiu:
  header:
  #页面头
    title: 云秀
  #每页数量
  pageSize: 1