server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    # 时间格式化
    date-format: yyyy-MM-dd
    # 时区
    time-zone: GMT+8
    locale: zh_CN
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

yunxiu:
  header:
    title: 云秀