server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://101.201.150.84:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: blog
    password: FieG6LWZ5FyErHhy
  jackson:
    # 时间格式化
    date-format: yyyy-MM-dd
    # 时区
    time-zone: GMT+8
    locale: zh_CN
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

yunxiu:
  header:
  #页面头
    title: 云秀
  #每页数量
  pageSize: 1

  github:
    client_id: cee7169b77fc23c392a0
    client_secret: 49347f6e0db42a00846275627853a328938ebf01
    callback: http://127.0.0.1:8088/gitHub
  qq:
    app_id: 101770145
    app_key: 3374e799e4424ae45de97d2c1aee42cf
    callback: http://127.0.0.1:8088/QQLogin

